export function getLabelById<
  T extends Record<string, 
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  any  
  >,
  IDKey extends keyof T,
  LangKey extends keyof T
>(
  array: T[],
  id: T[IDKey],
  idKey: IDKey,
  langKey: LangKey
): T[LangKey] | null {
  const found = array.find((item) => item[idKey] === id);
  return found ? found[langKey] : null;
}

export const conditions = [
  { condition_id: 1, cs: "Nové", en: "New" },
  { condition_id: 2, cs: "Ojeté", en: "Used" },
  { condition_id: 3, cs: "Havarované", en: "Damaged" },
  { condition_id: 4, cs: "Předváděcí", en: "Demo" },
  { condition_id: 5, cs: "Veterán", en: "Classic car" },
];

export const fuelList = [
  { fuel_id: 1, cs: "Benzín", en: "Petrol" },
  { fuel_id: 2, cs: "Nafta", en: "Diesel" },
  { fuel_id: 3, cs: "LPG + benzín", en: "LPG + petrol" },
  { fuel_id: 4, cs: "Elektro", en: "Electric" },
  { fuel_id: 5, cs: "Hybridní", en: "Hybrid" },
  { fuel_id: 6, cs: "CNG + benzín", en: "CNG + petrol" },
  { fuel_id: 7, cs: "Ethanol", en: "Ethanol" },
  { fuel_id: 8, cs: "Jiné", en: "Other" },
  { fuel_id: 9, cs: "Vodík", en: "Hydrogen" },
];

export const colorList = [
  { color_id: 1, cs: "Bílá", en: "White" },
  { color_id: 2, cs: "Žlutá", en: "Yellow" },
  { color_id: 3, cs: "Oranžová", en: "Orange" },
  { color_id: 4, cs: "Červená", en: "Red" },
  { color_id: 5, cs: "Vínová", en: "Burgundy" },
  { color_id: 6, cs: "Růžová", en: "Pink" },
  { color_id: 7, cs: "Fialová", en: "Purple" },
  { color_id: 8, cs: "Modrá", en: "Blue" },
  { color_id: 9, cs: "Zelená", en: "Green" },
  { color_id: 10, cs: "Hnědá", en: "Brown" },
  { color_id: 11, cs: "Šedá", en: "Gray" },
  { color_id: 12, cs: "Černá", en: "Black" },
  { color_id: 13, cs: "Béžová", en: "Beige" },
  { color_id: 14, cs: "Stříbrná", en: "Silver" },
  { color_id: 15, cs: "Zlatá", en: "Gold" },
  { color_id: 16, cs: "Jiná", en: "Other" },
  { color_id: 17, cs: "Bronzová", en: "Bronze" },
];

export const airbagList = [
  { airbag_id: 1, cs: "1", en: "1" },
  { airbag_id: 2, cs: "2", en: "2" },
  { airbag_id: 3, cs: "4", en: "4" },
  { airbag_id: 4, cs: "6", en: "6" },
  { airbag_id: 5, cs: "7", en: "7" },
  { airbag_id: 6, cs: "8", en: "8" },
  { airbag_id: 7, cs: "9", en: "9" },
  { airbag_id: 8, cs: "10", en: "10" },
  { airbag_id: 9, cs: "12", en: "12" },
  { airbag_id: 10, cs: "14", en: "14" },
];

export const airconditionList = [
  { aircondition_id: 1, cs: "Bez klimatizace", en: "No air conditioning" },
  { aircondition_id: 2, cs: "Manuální", en: "Manual" },
  { aircondition_id: 3, cs: "Automatická", en: "Automatic" },
  { aircondition_id: 4, cs: "Dvouzónová automatická", en: "Dual-zone automatic" },
  { aircondition_id: 5, cs: "Třízónová automatická", en: "Tri-zone automatic" },
  { aircondition_id: 6, cs: "Čtyřzónová automatická", en: "Four-zone automatic" },
];

export const stateList = [
  { id: 1, cs: "Česká republika", en: "Czech Republic" },
  { id: 2, cs: "Slovenská republika", en: "Slovakia" },
  { id: 3, cs: "Francie", en: "France" },
  { id: 4, cs: "Itálie", en: "Italy" },
  { id: 5, cs: "Německo", en: "Germany" },
  { id: 6, cs: "Rakousko", en: "Austria" },
  { id: 7, cs: "Švýcarsko", en: "Switzerland" },
  { id: 8, cs: "Holandsko", en: "Netherlands" },
  { id: 9, cs: "Lucembursko", en: "Luxembourg" },
  { id: 10, cs: "Jiná", en: "Other" },
  { id: 11, cs: "Belgie", en: "Belgium" },
  { id: 12, cs: "Španělsko", en: "Spain" },
  { id: 13, cs: "Dánsko", en: "Denmark" },
  { id: 14, cs: "Nedohledatelný původ", en: "Unknown origin" },
  { id: 15, cs: "USA", en: "USA" },
  { id: 16, cs: "Švédsko", en: "Sweden" },
  { id: 17, cs: "Polsko", en: "Poland" },
];

export const serviceBookList = [
  { id: 1, cs: "Ano", en: "Yes" },
  { id: 2, cs: "Ne", en: "No" },
];

export const gearboxLevelList = [
  { id: 3, cs: "3 stupňová a méně", en: "3-speed and less" },
  { id: 4, cs: "4 stupňová", en: "4-speed" },
  { id: 5, cs: "5 stupňová", en: "5-speed" },
  { id: 6, cs: "6 stupňová", en: "6-speed" },
  { id: 7, cs: "7 stupňová", en: "7-speed" },
  { id: 8, cs: "8 stupňová a více", en: "8-speed and more" },
];

export const gearboxAutoTypeList = [
  { id: 1, cs: "automatická", en: "automatic" },
  { id: 2, cs: "dvouspojková (DSG)", en: "dual-clutch (DSG)" },
  { id: 3, cs: "hydrodynamická", en: "hydrodynamic" },
  { id: 4, cs: "variátor (CVT)", en: "continuously variable (CVT)" },
];

export const gearboxList = [
  { id: 1, cs: "Manuální", en: "Manual" },
  { id: 2, cs: "Poloautomatická", en: "Semi-automatic" },
  { id: 3, cs: "Automatická", en: "Automatic" },
];

export const firstOwnerList = [
  { id: 1, cs: "Ano", en: "Yes" },
  { id: 2, cs: "Ne", en: "No" },
];

export const equipment = [
  { id: 3, cs: "Kožené čalounění", en: "Leather upholstery" },
  { id: 4, cs: "Imobilizér", en: "Immobilizer" },
  { id: 5, cs: "Navigační systém", en: "Navigation system" },
  { id: 6, cs: "Střešní okno", en: "Sunroof" },
  { id: 7, cs: "Centrální zamykání", en: "Central locking" },
  { id: 8, cs: "ABS", en: "ABS" },
  { id: 13, cs: "El. ovládání zrcátek", en: "Electric mirror control" },
  { id: 15, cs: "ESP", en: "ESP" },
  { id: 16, cs: "Litá kola", en: "Alloy wheels" },
  { id: 17, cs: "Tempomat", en: "Cruise control" },
  { id: 18, cs: "Záruka", en: "Warranty" },
  { id: 22, cs: "Alarm", en: "Alarm" },
  { id: 23, cs: "Alarm s dálkovým ovládáním", en: "Remote alarm" },
  { id: 24, cs: "Dálkové centrální zamykání", en: "Remote central locking" },
  { id: 25, cs: "Bezpečnostní pískování oken", en: "Window etching" },
  { id: 26, cs: "LPG v TP", en: "LPG registered" },
  { id: 27, cs: "Multifunkční volant", en: "Multifunction steering wheel" },
  { id: 28, cs: "Autorádio", en: "Car radio" },
  { id: 30, cs: "Palubní počítač", en: "On-board computer" },
  { id: 31, cs: "Parkovací asistent", en: "Parking assistant" },
  { id: 32, cs: "Posilovač řízení", en: "Power steering" },
  { id: 33, cs: "Přídavná světla", en: "Additional lights" },
  { id: 36, cs: "Nastavitelná sedadla", en: "Adjustable seats" },
  { id: 37, cs: "Nastavitelný volant", en: "Adjustable steering wheel" },
  { id: 38, cs: "Střešní nosič", en: "Roof rack" },
  { id: 39, cs: "Tónovaná skla", en: "Tinted windows" },
  { id: 40, cs: "Vyhřívaná zrcátka", en: "Heated mirrors" },
  { id: 41, cs: "Vyhřívané čelní sklo", en: "Heated windshield" },
  { id: 42, cs: "Vyhřívaná sedadla", en: "Heated seats" },
  { id: 43, cs: "Xenony", en: "Xenon headlights" },
  { id: 44, cs: "Zámek řadící páky", en: "Gear shift lock" },
  { id: 45, cs: "Závěsné zařízení v TP", en: "Tow bar registered" },
  { id: 46, cs: "Nožní startér", en: "Foot starter" },
  { id: 47, cs: "El. startér", en: "Electric starter" },
  { id: 48, cs: "Variátor", en: "CVT (variator)" },
  { id: 49, cs: "Katalyzátor", en: "Catalytic converter" },
  { id: 50, cs: "Plexi štít", en: "Plexiglass shield" },
  { id: 51, cs: "El. ovládání oken", en: "Electric windows" },
  { id: 54, cs: "Příprava pro autorádio", en: "Radio preparation" },
  { id: 56, cs: "CD přehrávač", en: "CD player" },
  { id: 57, cs: "CD měnič", en: "CD changer" },
  { id: 58, cs: "Televize", en: "TV" },
  { id: 59, cs: "Přehrávač videa", en: "Video player" },
  { id: 60, cs: "1 monitor", en: "1 monitor" },
  { id: 61, cs: "2 monitory", en: "2 monitors" },
  { id: 62, cs: "3 monitory", en: "3 monitors" },
  { id: 63, cs: "4 monitory", en: "4 monitors" },
  { id: 64, cs: "Telefon", en: "Telephone" },
  { id: 65, cs: "Příprava pro telefon", en: "Phone preparation" },
  { id: 66, cs: "CB vysílačka", en: "CB radio" },
  { id: 67, cs: "Mikrofon", en: "Microphone" },
  { id: 68, cs: "Zaslepení zámků", en: "Lock cover" },
  { id: 72, cs: "Otevíratelná střecha", en: "Opening roof" },
  { id: 74, cs: "Ski box", en: "Ski box" },
  { id: 75, cs: "Ostřikovače světlometů", en: "Headlight washers" },
  { id: 76, cs: "Ochranné rámy", en: "Protective frames" },
  { id: 77, cs: "Střešní spoiler", en: "Roof spoiler" },
  { id: 79, cs: "Zadní stěrač", en: "Rear wiper" },
  { id: 80, cs: "Chladnička", en: "Refrigerator" },
  { id: 81, cs: "Kávovar", en: "Coffee maker" },
  { id: 83, cs: "Mikrovlná trouba", en: "Microwave oven" },
  { id: 84, cs: "WC", en: "Toilet" },
  { id: 85, cs: "Ohřívač vody", en: "Water heater" },
  { id: 86, cs: "Zásuvka na 220 V", en: "220V socket" },
  { id: 87, cs: "Nezávislé topení", en: "Auxiliary heating" },
  { id: 88, cs: "Nezávislé topení s čas. předehřívačem", en: "Auxiliary heating with timer" },
  { id: 89, cs: "Vyjímatelná zadní sedadla", en: "Removable rear seats" },
  { id: 90, cs: "Příprava pro isofix", en: "Isofix preparation" },
  { id: 91, cs: "Síťka mezistěny zavazadlového prostoru", en: "Cargo net" },
  { id: 92, cs: "Sportovní sedadla", en: "Sport seats" },
  { id: 93, cs: "El. seřiditelná sedadla", en: "Electric adjustable seats" },
  { id: 94, cs: "Výškově nastavitelná sedadla", en: "Height-adjustable seats" },
  { id: 95, cs: "Podélný posuv sedadel", en: "Longitudinal seat adjustment" },
  { id: 96, cs: "Sedadla výsuvná do uličky", en: "Sliding aisle seats" },
  { id: 97, cs: "Výsuvné opěrky hlav", en: "Adjustable headrests" },
  { id: 98, cs: "Kožené potahy", en: "Leather seats" },
  { id: 99, cs: "Dřevěné obložení", en: "Wood trim" },
  { id: 103, cs: "Satelitní navigace", en: "Satellite navigation" },
  { id: 105, cs: "Tažné zařízení", en: "Tow hitch" },
  { id: 106, cs: "Elektronická uzávěrka diferenciálu (EDS)", en: "Electronic differential lock (EDS)" },
  { id: 108, cs: "Senzor stěračů", en: "Rain sensor" },
  { id: 118, cs: "Otáčkoměr", en: "Tachometer" },
  { id: 119, cs: "Sportovní podvozek", en: "Sports suspension" },
  { id: 120, cs: "Laděný výfuk", en: "Tuned exhaust" },
  { id: 124, cs: "Hydraulika pro sklápění", en: "Hydraulics for tipping" },
  { id: 127, cs: "Jednoduchá nádrž do 400 l nafty", en: "Single tank up to 400 l diesel" },
  { id: 128, cs: "Dvojitá nádrž do 800 l nafty", en: "Double tank up to 800 l diesel" },
  { id: 137, cs: "Intardér", en: "Intarder" },
  { id: 138, cs: "Retardér", en: "Retarder" },
  { id: 139, cs: "Dálkový start", en: "Remote start" },
  { id: 142, cs: "Protiprokluzový systém kol (ASR)", en: "Anti-slip regulation (ASR)" },
  { id: 143, cs: "Výbava ADR", en: "ADR equipment" },
  { id: 145, cs: "Uzávěrka mezinápravového diferenciálu", en: "Inter-axle differential lock" },
  { id: 146, cs: "Venkovní teploměr", en: "Outdoor thermometer" },
  { id: 147, cs: "Vnitřní teploměr", en: "Indoor thermometer" },
  { id: 149, cs: "Padáky", en: "Parachutes" },
  { id: 150, cs: "Kufry", en: "Cases" },
  { id: 151, cs: "Brašny", en: "Bags" },
  { id: 152, cs: "Vzduchové ovládání dveří", en: "Pneumatic door control" },
  { id: 153, cs: "Regulace výšky podvozku", en: "Chassis height adjustment" },
  { id: 154, cs: "Regulace tuhosti podvozku", en: "Chassis stiffness adjustment" },
  { id: 155, cs: "Tlumič řízení", en: "Steering damper" },
  { id: 156, cs: "Konvenční odpružení", en: "Conventional suspension" },
  { id: 158, cs: "Vzduchové odpružení", en: "Air suspension" },
  { id: 159, cs: "Tachograf", en: "Tachograph" },
  { id: 161, cs: "Naviják", en: "Winch" },
  { id: 183, cs: "Kabina trambusová", en: "Cab-over cab" },
  { id: 184, cs: "Kabina kapotovaná", en: "Conventional cab" },
  { id: 187, cs: "Mlhovky", en: "Fog lights" },
  { id: 188, cs: "Zadní mlhovka", en: "Rear fog light" },
  { id: 189, cs: "Uzávěrka zadního diferenciálu", en: "Rear differential lock" },
  { id: 190, cs: "Uzávěrka předního diferenciálu", en: "Front differential lock" },
  { id: 191, cs: "Boční nášlapy", en: "Side steps" },
  { id: 192, cs: "Šnorchl", en: "Snorkel" },
  { id: 193, cs: "S couvacím světlem", en: "With reversing light" },
  { id: 194, cs: "Vidlice 7-pol", en: "7-pin connector" },
  { id: 195, cs: "Vidlice 13-pol", en: "13-pin connector" },
  { id: 196, cs: "Opěrné kolečko", en: "Jockey wheel" },
  { id: 197, cs: "Opěrné nohy", en: "Support legs" },
  { id: 198, cs: "Plachta", en: "Tarpaulin" },
  { id: 199, cs: "Laminátové víko", en: "Fiberglass lid" },
  { id: 200, cs: "Kotvící oka", en: "Anchoring eyes" },
  { id: 201, cs: "Rezervní kolo", en: "Spare wheel" },
  { id: 202, cs: "Zakládací klíny", en: "Wheel chocks" },
  { id: 203, cs: "Nebrzděný", en: "Unbraked" },
  { id: 204, cs: "Brzděný", en: "Braked" },
  { id: 205, cs: "Trubková/jeklová oj", en: "Tube/square drawbar" },
  { id: 206, cs: "V oj", en: "V drawbar" },
  { id: 207, cs: "Výškově stavitelná oj", en: "Height-adjustable drawbar" },
  { id: 208, cs: "Překližkové bočnice", en: "Plywood sides" },
  { id: 209, cs: "Plechové bočnice", en: "Metal sides" },
  { id: 210, cs: "Hliníkové bočnice", en: "Aluminum sides" },
  { id: 211, cs: "Bez bočnic", en: "Without sides" },
  { id: 212, cs: "Start/Stop systém", en: "Start/Stop system" },
  { id: 213, cs: "Asistent rozjezdu do kopce", en: "Hill-start assist" },
  { id: 214, cs: "Parkovací senzory", en: "Parking sensors" },
  { id: 215, cs: "Isofix", en: "Isofix" },
  { id: 217, cs: "Panoramatická střecha", en: "Panoramic roof" },
  { id: 218, cs: "Bezklíčkové ovládání", en: "Keyless entry" },
  { id: 219, cs: "Rádio", en: "Radio" },
  { id: 220, cs: "Originální autorádio", en: "Original car radio" },
  { id: 221, cs: "Dělená zadní sedadla", en: "Split rear seats" },
  { id: 222, cs: "Asistent při jízdě ze svahu", en: "Hill descent control" },
  { id: 223, cs: "Klimatizovaná přihrádka", en: "Air-conditioned glovebox" },
  { id: 224, cs: "Výškově nastavitelné sedadlo řidiče", en: "Height-adjustable driver's seat" },
  { id: 225, cs: "Automatická uzávěrka diferenciálu", en: "Automatic differential lock" },
  { id: 226, cs: "Deaktivace airbagu spolujezdce", en: "Passenger airbag deactivation" },
  { id: 227, cs: "Kožená sedadla", en: "Leather seats" },
  { id: 228, cs: "LED denní svícení", en: "LED daytime running lights" },
  { id: 231, cs: "Parkovací kamera", en: "Parking camera" },
  { id: 232, cs: "Adaptivní tempomat", en: "Adaptive cruise control" },
  { id: 233, cs: "Sklápěč", en: "Tipper" },
  { id: 238, cs: "LED světlomety plnohodnotné", en: "Full LED headlights" },
  { id: 240, cs: "Bi-xenony", en: "Bi-xenon headlights" },
  { id: 241, cs: "Vyhřívaný volant", en: "Heated steering wheel" },
  { id: 242, cs: "Masážní sedadla", en: "Massage seats" },
  { id: 243, cs: "USB", en: "USB" },
  { id: 244, cs: "Bluetooth", en: "Bluetooth" },
  { id: 245, cs: "El. sklopná zrcátka", en: "Electric folding mirrors" },
  { id: 246, cs: "El. ovládaný kufr", en: "Electric trunk lid" },
  { id: 247, cs: "Natáčecí světlomety", en: "Adaptive headlights" },
  { id: 248, cs: "Automatické svícení", en: "Automatic headlights" },
  { id: 249, cs: "Senzor opotřebení brzd. destiček", en: "Brake pad wear sensor" },
  { id: 250, cs: "Hlídání mrtvého úhlu", en: "Blind spot monitoring" },
  { id: 251, cs: "Sledování jízdního pruhu", en: "Lane departure warning" },
  { id: 252, cs: "Nouzové brždění", en: "Emergency braking" },
  { id: 253, cs: "Vstup paměťové karty", en: "Memory card slot" },
  { id: 254, cs: "DVD přehrávač", en: "DVD player" },
  { id: 255, cs: "Sledování únavy řidiče", en: "Driver fatigue monitoring" },
  { id: 257, cs: "Senzor tlaku v pneumatikách", en: "Tire pressure monitoring system" },
  { id: 258, cs: "Malý kožený paket", en: "Small leather package" },
  { id: 259, cs: "360° monitorovací systém (AVM)", en: "360° monitoring system (AVM)" },
  { id: 261, cs: "Rozpoznávání dopravních značek", en: "Traffic sign recognition" },
  { id: 262, cs: "Upozornění na přijíždějící vozidla při couvání (RCTA)", en: "Rear cross traffic alert (RCTA)" },
  { id: 263, cs: "Asistent stability přívěsu (TSA)", en: "Trailer stability assist (TSA)" },
  { id: 264, cs: "Elektrochromatické vnitřní zpětné zrcátko", en: "Auto-dimming interior rearview mirror" },
  { id: 265, cs: "Zatmavená zadní skla", en: "Tinted rear windows" },
  { id: 266, cs: "Bezdrátová nabíječka mobilních telefonů (Qi)", en: "Wireless phone charger (Qi)" },
  { id: 267, cs: "Roletky na zadní okna", en: "Rear window sunshades" },
  { id: 268, cs: "Aktivní kapota", en: "Active hood" },
  { id: 270, cs: "Přístrojová deska s barevným displejem", en: "Instrument panel with color display" },
  { id: 271, cs: "Premiový audiosystém", en: "Premium sound system" },
  { id: 273, cs: "Motorová brzda", en: "Engine brake" },
  { id: 274, cs: "Odvětrávání sedadel", en: "Seat ventilation" },
  { id: 275, cs: "Denní svícení", en: "Daytime running lights" },
  { id: 276, cs: "Ambientní LED osvětlení interiéru", en: "Ambient LED interior lighting" },
  { id: 277, cs: "Android Auto", en: "Android Auto" },
  { id: 278, cs: "Apple Car Play", en: "Apple CarPlay" },
  { id: 279, cs: "Asistent pro jízdu v koloně", en: "Traffic jam assist" },
  { id: 280, cs: "Asistent pro vedení vozu v jízdních pruzích", en: "Lane keeping assist" },
  { id: 281, cs: "Parkovací senzory přední", en: "Front parking sensors" },
  { id: 282, cs: "Parkovací senzory zadní", en: "Rear parking sensors" },
  { id: 283, cs: "Digitální příjem rádia (DAB)", en: "Digital radio reception (DAB)" },
  { id: 284, cs: "Digitální přístrojový štít", en: "Digital instrument cluster" },
  { id: 285, cs: "Dojezdové rezervní kolo", en: "Space-saver spare wheel" },
  { id: 286, cs: "Dotykové ovládání palubního počítače", en: "Touch control of onboard computer" },
  { id: 287, cs: "El. parkovací brzda", en: "Electronic parking brake" },
  { id: 288, cs: "Funkce plynulého dovírání dveří", en: "Soft-close doors" },
  { id: 289, cs: "Head-up display", en: "Head-up display" },
  { id: 290, cs: "Hlasové ovládání palubního počítače", en: "Voice control of onboard computer" },
  { id: 291, cs: "Laserová světla", en: "Laser headlights" },
  { id: 292, cs: "LED adaptivní světlomety", en: "LED adaptive headlights" },
  { id: 293, cs: "LED matrixové světlomety", en: "LED matrix headlights" },
  { id: 294, cs: "Mobilní připojení", en: "Mobile connectivity" },
  { id: 295, cs: "Ovládání vybraných funkcí vozu gesty", en: "Gesture control" },
  { id: 296, cs: "Pádla řazení na volantu", en: "Steering wheel shift paddles" },
  { id: 297, cs: "Paměť nastavení sedadla řidiče", en: "Driver seat memory settings" },
  { id: 298, cs: "Plnohodnotné rezervní kolo", en: "Full-size spare wheel" },
  { id: 299, cs: "Systém nouzového zastavení", en: "Emergency stop system" },
  { id: 300, cs: "Volba jízdního režimu", en: "Drive mode selector" },
  { id: 301, cs: "Vyhřívané trysky ostřikovačů skla", en: "Heated windshield washer nozzles" },
  { id: 302, cs: "Zadní loketní opěrka", en: "Rear armrest" },
  { id: 303, cs: "Aktivní asistent řízení", en: "Active steering assist" },
  { id: 304, cs: "Akustická výstraha při couvání", en: "Acoustic reverse warning" },
  { id: 305, cs: "Asistent pro odbočování", en: "Turning assistant" },
  { id: 306, cs: "Asistent udržování odstupu", en: "Distance keeping assist" },
  { id: 307, cs: "Ochrana proti odcizení a vloupání", en: "Anti-theft protection" },
  { id: 308, cs: "Prediktivní tempomat", en: "Predictive cruise control" },
  { id: 309, cs: "Zásuvka pro přídavné spotřebiče", en: "Socket for auxiliary devices" },
  { id: 310, cs: "Adaptivní regulace podvozku", en: "Adaptive chassis control" },
  { id: 311, cs: "Asistent změny jízdního pruhu", en: "Lane change assistant" },
  { id: 312, cs: "Automatické přepínání dálkových světel", en: "Automatic high beam assist" },
  { id: 313, cs: "El. seřiditelné sedadlo řidiče", en: "Electrically adjustable driver's seat" },
  { id: 314, cs: "Elektrické dovírání zavazadlového prostoru", en: "Electric trunk closing" },
  { id: 315, cs: "El. nastavitelná zadní sedadla", en: "Electrically adjustable rear seats" },
  { id: 316, cs: "Elektrické tažné zařízení", en: "Electric tow bar" },
  { id: 317, cs: "Digitální přístrojová deska", en: "Digital instrument panel" },
  { id: 318, cs: "Ventilovaná zadní sedadla", en: "Ventilated rear seats" },
  { id: 319, cs: "Wifi hotspot", en: "Wi-Fi hotspot" },
  { id: 320, cs: "Vyhřívaná zadní sedadla", en: "Heated rear seats" },
  { id: 321, cs: "Třetí řada sedadel", en: "Third row of seats" },
  { id: 322, cs: "Tepelné čerpadlo", en: "Heat pump" },
  { id: 323, cs: "Multimediální systém bez navigace", en: "Multimedia system without navigation" },
  { id: 324, cs: "Front Assist", en: "Front Assist" },
  { id: 325, cs: "Lane Assist", en: "Lane Assist" },
  { id: 326, cs: "Akustická skla", en: "Acoustic glass" },
  { id: 327, cs: "Příplatkový audiosystém", en: "Optional sound system" },
  { id: 328, cs: "Sedadla Alcantara", en: "Alcantara seats" },
  { id: 329, cs: "Sportovní paket", en: "Sport package" },
  { id: 330, cs: "Elektrické dovírání dveří", en: "Electric soft-close doors" }
];

